[package]
name = "esp32-sound-monitor"
version = "0.1.0"
authors = ["Your Name <you@example.com>"]
edition = "2021"

[dependencies]
# System and logging services
esp-idf-svc = { version = "0.52.1", features = ["alloc", "experimental"] }
# Hardware abstraction layer
esp-idf-hal = { version = "0.46.2", features = ["adc-oneshot-legacy"] }
# System bindings
esp-idf-sys = { version = "0.37.1", features = ["binstart"] }

embedded-svc = "0.29.0"
embedded-io = "0.7.1"
heapless = "0.8"

fake_sensors = { path = "./src/fake_sensors" }
daq_engine = { path = "./src/daq_engine" }
storage = { path = "./src/storage" }

[features]
default = ["adc-oneshot-legacy"]
adc-oneshot-legacy = ["esp-idf-hal/adc-oneshot-legacy"]

[[package.metadata.esp-idf-sys.extra_components]]
remote_component = { name = "espressif/mdns", version = "1.2" }

[build-dependencies]
embuild = "0.33.0"

[profile.release]
opt-level = "s"

[profile.dev]
debug = true
opt-level = "z"